const menu = [
  {
    name: "Smoked Salmon",
    description:
      "potato pancake, creme fraiche, shallots, tomato, frisee, chives",
    type: "First",
    isVegan: false,
    isVegetarian: false,
    price: 24,
  },
  {
    name: "California Crudite",
    description: "market vegetables, chevre, creamy avocado dip, pita chips",
    type: "First",
    isVegan: false,
    isVegetarian: true,
    price: 23,
  },
  {
    name: "Baby Greens Salad",
    description: "easter egg radish, fines herbes, champagne vinaigrette",
    type: "First",
    isVegan: true,
    isVegetarian: true,
    price: 20,
  },
  {
    name: "Tuscan Kale Caesar",
    description: "romaine, radicchio, pecorino, breadcrumbs, garlic dressing",
    type: "First",
    isVegan: false,
    isVegetarian: false,
    price: 18,
  },
  {
    name: "Faroe Island Salmon",
    description: "royal trumpet mushrooms, asparagus, cippolini onions",
    type: "Second",
    isVegan: false,
    isVegetarian: false,
    price: 30,
  },
  {
    name: "Roasted Lemon Chicken",
    description: "yukon potato puree, blistered tomatoes, kalamata olives",
    type: "Second",
    isVegan: false,
    isVegetarian: false,
    price: 28,
  },
  {
    name: "Mediterranean Tuna Sandwich",
    description: "ahi tuna confit, arugula, giardiniera, herb mayo, fries",
    type: "Second",
    isVegan: false,
    isVegetarian: false,
    price: 25,
  },
  {
    name: "Gilder Burger",
    description:
      "Pat LaFrieda dry aged beef blend, cheddar, tomato, pickles, onion, aioli, fries",
    type: "Second",
    isVegan: false,
    isVegetarian: false,
    price: 26,
  },
  {
    name: "Grilled Chicken Sandwich",
    description: "caramelized onions, gruyere cheese, arugula, tomato, fries",
    type: "Second",
    isVegan: false,
    isVegetarian: false,
    price: 24,
  },
  {
    name: "Roasted Cauliflower",
    description: "heritage grains, fava beans, roasted tomatoes, agridolce",
    type: "Second",
    isVegan: true,
    isVegetarian: true,
    price: 22,
  },
  {
    name: "Soup of the Day (Cup/Bowl)",
    description: "",
    type: "Sides",
    isVegan: false,
    isVegetarian: false,
    price: "10 / 14", // could also be 14 depending on size
  },
  {
    name: "Small Greens Salad",
    description: "",
    type: "Sides",
    isVegan: true,
    isVegetarian: true,
    price: 10,
  },
  {
    name: "House-Made Milk Rolls",
    description: "",
    type: "Sides",
    isVegan: false,
    isVegetarian: true,
    price: 9,
  },
  {
    name: "Side of Mushrooms",
    description: "",
    type: "Sides",
    isVegan: true,
    isVegetarian: true,
    price: 8,
  },
  {
    name: "Side of Bacon",
    description: "",
    type: "Sides",
    isVegan: false,
    isVegetarian: false,
    price: 8,
  },
  {
    name: "Add Bacon or a Fried Egg",
    description: "",
    type: "Addons",
    isVegan: false,
    isVegetarian: false,
    price: 4,
  },
  {
    name: "Add Avocado or Mushrooms",
    description: "",
    type: "Addons",
    isVegan: true,
    isVegetarian: true,
    price: 4,
  },
  {
    name: "Add Chicken or Tuna Confit",
    description: "",
    type: "Addons",
    isVegan: false,
    isVegetarian: false,
    price: 10,
  },
  {
    name: "Add Salmon or Shrimp",
    description: "",
    type: "Addons",
    isVegan: false,
    isVegetarian: false,
    price: 12,
  },
  {
    name: "The Butterfly",
    description: "butterfly pea flower tea, lemonade",
    type: "Specialty Beverages",
    isVegan: true,
    isVegetarian: true,
    price: 10,
  },
  {
    name: "Cherry Lime Rickey",
    description: "amarena cherries, lime, soda",
    type: "Specialty Beverages",
    isVegan: true,
    isVegetarian: true,
    price: 10,
  },
  {
    name: "Bellini",
    description: "peach puree, sparkling white grape juice",
    type: "Specialty Beverages",
    isVegan: true,
    isVegetarian: true,
    price: 10,
  },
  {
    name: "Melon Mojito",
    description: "honeydew, mint, agave, lime",
    type: "Specialty Beverages",
    isVegan: true,
    isVegetarian: true,
    price: 10,
  },
  {
    name: "Zardetto Spritz",
    description: "prosecco, rhubarb-orange infused amaro",
    type: "Specialty Beverages",
    isVegan: true,
    isVegetarian: true,
    price: 16,
  },
  {
    name: "New York Style Cheesecake",
    description: "",
    type: "Desserts",
    isVegan: false,
    isVegetarian: true,
    price: 12,
  },
  {
    name: "Strawberry Panna Cotta",
    description: "",
    type: "Desserts",
    isVegan: true,
    isVegetarian: true,
    price: 12,
  },
  {
    name: "Chocolate Chip Skillet Cookie",
    description: "",
    type: "Desserts",
    isVegan: false,
    isVegetarian: true,
    price: 12,
  },
  {
    name: "Affogato",
    description: "",
    type: "Desserts",
    isVegan: false,
    isVegetarian: true,
    price: 8,
  },
];

export default menu;
